---
apiVersion: "v1"
kind: "Namespace"
metadata:
  name: "response-service"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "response-service"
  namespace: "steve-overflow"
  labels:
    app: "response-service"
spec:
  selector:
    matchLabels:
      app: "response-service"
  template:
    metadata:
      labels:
        app: "response-service"
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: response-config
        name: "response-service-sha256-1"
        image: "gcr.io/steveoverflow-289df/response-service:latest"
        resources:
          limits:
            cpu: "0.05"

---
apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "response-service-hpa-yrnk"
  namespace: "steve-overflow"
  labels:
    app: "response-service"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "response-service"
    apiVersion: "apps/v1"
  minReplicas: 2
  maxReplicas: 100
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      target:
        type: "Utilization"
        averageUtilization: 25
